/**
 * PulseAgent - Имитация работы ИИ-агента, который готовит материалы.
 */
const PulseAgent = {
    /**
     * Сгенерировать новый черновик на основе конкретной задачи
     */
    generateDraft: async function(task) {
        const globalSettings = await window.PulseAPI.getAgentSettings();
        console.log(`Using API Provider: ${globalSettings.provider} [Key: ${globalSettings.key ? '***' : 'empty'}]`);
        
        if (!task) {
            // Если задача не передана, берем первую из списка
            const tasks = await window.PulseAPI.getAgentTasks();
            task = tasks[0];
        }
        
        const isNews = task.type === 'news';
        const now = new Date();
        const timeStr = `${now.getHours()}:${now.getMinutes().toString().padStart(2, '0')}`;
        
        const topics = [
            { ru: "Квантовое превосходство", en: "Quantum Supremacy" },
            { ru: "Нейронные интерфейсы", en: "Neural Interfaces" },
            { ru: "Автономные города", en: "Autonomous Cities" },
            { ru: "Этика ИИ", en: "AI Ethics" },
            { ru: "Web 4.0 и децентрализация", en: "Web 4.0 & Decentralization" }
        ];
        
        const topic = topics[Math.floor(Math.random() * topics.length)];
        const stylePrefix = task.prompt.toLowerCase().includes('премиальный') ? 'Premium' : 'AI';
        
        const draft = {
            id: Date.now(),
            type: task.type,
            status: 'pending',
            time: timeStr,
            date: "02 Апр 2026",
            readTime: isNews ? "2 мин" : "8 мин",
            title: { 
                ru: `[${task.name}] ${topic.ru}`, 
                en: `[${task.name}] ${topic.en}` 
            },
            excerpt: { 
                ru: `Анализ темы "${topic.ru}" на основе задачи "${task.name}". Промпт: ${task.prompt.substring(0, 30)}...`, 
                en: `Analysis of "${topic.en}" based on task "${task.name}". Prompt: ${task.prompt.substring(0, 30)}...` 
            },
            content: {
                ru: `<h1>${topic.ru}</h1><p>Сгенерировано по задаче: <strong>${task.name}</strong>. Промпт: ${task.prompt}</p>`,
                en: `<h1>${topic.en}</h1><p>Generated by task: <strong>${task.name}</strong>. Prompt: ${task.prompt}</p>`
            },
            image: task.useImage ? (isNews ? 'agency_tech_abstract.png' : 'ui_dashboard_preview.png') : null
        };

        if (window.PulseAPI) {
            await window.PulseAPI.addPending(draft);
        }
        
        return draft;
    }
};

// Экспортируем глобально
window.PulseAgent = PulseAgent;
